export const RESTAURANT_CATEGORIES = [
  '和食',
  '寿司',
  'ラーメン',
  '焼肉',
  'イタリアン',
  'フレンチ',
  '中華',
  '韓国料理',
  'カフェ',
  '居酒屋',
  'バー',
  'ファストフード',
  'カレー',
  'タイ料理',
  'インド料理',
  'ベトナム料理',
  'メキシコ料理',
  'スペイン料理',
  'パン屋',
  'スイーツ',
  'その他',
] as const;

export const PRICE_RANGES = [
  { value: 1, label: '¥', description: '〜1,000円' },
  { value: 2, label: '¥¥', description: '1,000円〜3,000円' },
  { value: 3, label: '¥¥¥', description: '3,000円〜10,000円' },
  { value: 4, label: '¥¥¥¥', description: '10,000円〜' },
] as const;

export const SUGGESTED_TAGS = [
  'デート',
  '記念日',
  '女子会',
  '家族',
  '接待',
  '一人飯',
  'ランチ',
  'ディナー',
  'テイクアウト',
  'テラス席',
  '個室あり',
  '駅近',
  '深夜営業',
  '子連れOK',
  'ペット可',
  'コスパ良し',
  '雰囲気良し',
  'インスタ映え',
  '隠れ家',
  '老舗',
];
